#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinAndroidModule.Resource", IsApplication=true)]

namespace XamarinAndroidModule
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030000
			public const int my_blue = 2130903040;
			
			// aapt resource value: 0x7f030003
			public const int my_gray = 2130903043;
			
			// aapt resource value: 0x7f030001
			public const int my_green = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int my_purple = 2130903042;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int CreateBtn = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int MainLayout = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int NameEdt = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int SpecialtyEdt = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int CreateTitle = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int InvalidName = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int InvalidSpecialty = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int Main_Title = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int NameHint = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int SpecialtyHint = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
