#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinAndroidModule.Resource", IsApplication=true)]

namespace XamarinAndroidModule
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int programmers_array = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int my_blue = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int my_gray = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int my_green = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int my_purple = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int rocket = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090004
			public const int CreateBtn = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int ImageSpinner = 2131296259;
			
			// aapt resource value: 0x7f090000
			public const int MainLayout = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int NameEdt = 2131296257;
			
			// aapt resource value: 0x7f090005
			public const int ProgListView = 2131296261;
			
			// aapt resource value: 0x7f090002
			public const int SpecialtyEdt = 2131296258;
			
			// aapt resource value: 0x7f090006
			public const int progImg = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int progNameTxt = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int progSpecialtyTxt = 2131296264;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ProgrammerRow = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int rocket = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060004
			public const int CreateTitle = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int InvalidName = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int InvalidSpecialty = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int Main_Title = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int NameHint = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int SpecialtyHint = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Theme_AlsetAndroidTheme = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
